### PR TITLE
Added Gallery and Footer

### PR DESCRIPTION
**Pull request by ericm**
Theres some embeds in the footer for extra info
image
image
image

### CODE REVIEW

**Comment by ocanty** [comment]
Could you remove the margins in between the gallery photos?

**Comment by ocanty** [comment]
> Could you remove the margins in between the gallery photos?

These 
image

**Comment by ericm** [comment]
Sure

**Comment by ocanty** [comment]
screenshot of what the discord widget looks like rn pls

**Comment by ericm** [comment]
image

**Comment by ocanty** [comment]
image

have to keep a voice channel named like this because discord is bad

**Comment by ocanty** [comment]
think you could also spread the gallery to stop the black space on either side? this would also reduce the length of the page, 2 rows would be best. no need to make a carousel, just occupy the space as necessary

less blank space > slightly obscured photos

image

ideally should emulate the behavior of the old website, but keep image height consistent, you can vary the width as needed (in order to keep aspect ratio)

**Comment by ericm** [comment]
image

**Comment by ocanty** [comment]
max 2 rows?, just minimize amount of black space

**Comment by ericm** [comment]
The images are pulled from the wiki so it doesnt really have any control over how many images there are. when u resize it changes the amount of images per row for obvious reasons so no real way to limit it to 2 rows

**Comment by ocanty** [comment]
can you not set the height of the gallery element to 2x the height of an image and use overflow hidden

**Comment by ericm** [comment]
Theres going to be more images added at some point so I dont think it should be limited to 2. last thing we want is to add images to the site and they not show up

**Comment by ericm** [comment]
How about a button that expands the gallery if clicked

**Comment by gal** [comment]
Maybe for now at least only show the most recent X photos from the wiki?

**Comment by ocanty** [comment]
image

as long as the black gets hidden idm what is done

**Comment by ericm** [comment]
image

**Pull request merged**
